GEMINI_API_KEY = "AIzaSyA24PAbubtMSldRekGHRar2wJXOFWlPQ-A"
connection_string = "mongodb+srv://phh242:hacknyu2025password@hacknyu2025.1lcf2.mongodb.net/?retryWrites=true&w=majority&appName=hacknyu2025"
